/**
 * Word database for WordsMaster game
 * Organized by difficulty levels
 */

const WORDS = [
  // Easy words (4-5 letters)
  "apple",
  "beach",
  "chair",
  "dance",
  "eagle",
  "fruit",
  "grape",
  "house",
  "joint",
  "tree",
  "blue",
  "jump",
  "frog",
  "desk",
  "lamp",
  "bird",
  "fish",
  "book",
  "star",
  "moon",
  "wind",
  "rain",
  "fire",
  "soil",
  "path",
  "leaf",
  "root",
  "sand",
  "wave",
  "city",
  "town",
  "road",
  "hill",
  "lake",
  "river",
  "ship",
  "boat",
  "flag",
  "sign",
  "idea",
  "plan",
  "goal",
  "task",
  "form",
  "list",
  "data",
  "code",
  "file",
  "user",
  "time",
  "date",
  "week",
  "year",
  "hour",
  "mile",
  "foot",
  "inch",
  "yard",
  "face",
  "hand",
  "head",
  "body",
  "mind",
  "soul",
  "life",
  "love",
  "hate",
  "fear",
  "hope",
  "play",
  "work",
  "draw",
  "sing",
  "read",
  "write",
  "talk",
  "walk",
  "stop",
  "open",
  "close",
  "find",
  "lose",
  "keep",
  "give",
  "take",
  "make",
  "send",
  "call",
  "help",
  "need",
  "want",
  // Removed at runtime via AMBIGUOUS_WORDS: "feel",
  "know",
  "show",
  "tell",
  "hold",
  "turn",
  "move",
  "grow",
  "live",
  "stay",
  "fall",
  "rise",
  "hear",
  "look",
  "seem",
  "mean",
  "wait",
  "meet",

  // Medium words (6-7 letters)
  "planet",
  "forest",
  "garden",
  "valley",
  "bridge",
  "street",
  "market",
  "school",
  "office",
  "church",
  "window",
  "mirror",
  "bottle",
  "basket",
  "pencil",
  "tablet",
  "camera",
  "laptop",
  "system",
  "server",
  "number",
  "letter",
  "phrase",
  "string",
  "object",
  "module",
  "method",
  "result",
  "output",
  "input",
  "moment",
  "season",
  "minute",
  "second",
  "decade",
  "degree",
  "weight",
  "height",
  "length",
  "volume",
  "animal",
  "people",
  "family",
  "friend",
  "leader",
  "artist",
  "writer",
  "doctor",
  "player",
  "singer",
  "beauty",
  "wisdom",
  "honesty",
  "courage",
  "freedom",
  "justice",
  "patience",
  "respect",
  "success",
  "failure",
  "action",
  "change",
  "create",
  "design",
  "develop",
  "manage",
  "reduce",
  "expand",
  "protect",
  "support",
  "arrive",
  "depart",
  "attend",
  "accept",
  "reject",
  "inform",
  "invite",
  "expect",
  "forget",
  "remind",
  "listen",
  "notice",
  "wonder",
  "decide",
  "select",
  "obtain",
  "prepare",
  "perform",
  "provide",
  "receive",
  "explain",
  "discuss",
  "compare",
  "analyze",
  "imagine",
  "realize",
  "believe",
  "express",
  "reflect",
  "resolve",

  // Hard words (8+ letters)
  "mountain",
  "continent",
  "universe",
  "adventure",
  "discovery",
  "invention",
  "technology",
  "education",
  "knowledge",
  "information",
  "structure",
  "mechanism",
  "algorithm",
  "parameter",
  "interface",
  "component",
  "operation",
  "procedure",
  "statement",
  "function",
  "situation",
  "condition",
  "character",
  "personality",
  "experience",
  "generation",
  "population",
  "environment",
  "atmosphere",
  "landscape",
  "community",
  "relationship",
  "connection",
  "communication",
  "conversation",
  "development",
  "improvement",
  "achievement",
  "recognition",
  "appreciation",
  "understand",
  "appreciate",
  "participate",
  "communicate",
  "demonstrate",
  "distinguish",
  "investigate",
  "collaborate",
  "coordinate",
  "contribute",
  "anticipate",
  "facilitate",
  "incorporate",
  "manipulate",
  "negotiate",
  "prioritize",
  "recalibrate",
  "reconfigure",
  "reconstruct",
  "redistribute",
  "accessibility",
  "accountability",
  "adaptability",
  "affordability",
  "availability",
  "compatibility",
  "connectivity",
  "credibility",
  "durability",
  "flexibility",
  "fundamental",
  "influential",
  "instrumental",
  "intellectual",
  "intermittent",
  "jurisdiction",
  "legislation",
  "manipulation",
  "methodology",
  "notification",
  "organization",
  "participation",
  "performance",
  "perspective",
  "preliminary",
  "probability",
  "productivity",
  "professional",
  "responsibility",
];

// Words to exclude because their letters can form other valid words easily
// Extend this list as needed. Examples:
// - "feel" ↔ "flee" (even if one variant isn't currently in WORDS, it's commonly confused)
// - "file" ↔ "life"
// - "sign" ↔ "sing"
const AMBIGUOUS_WORDS = ["feel", "file", "life", "sign", "sing"];

// Cleaned list used by the game
const SAFE_WORDS = WORDS.filter((w) => !AMBIGUOUS_WORDS.includes(w));

// Word categories for future enhancements
const WORD_CATEGORIES = {
  nature: [
    "tree",
    "leaf",
    "river",
    "mountain",
    "ocean",
    "forest",
    "flower",
    "butterfly",
  ],
  technology: [
    "computer",
    "internet",
    "software",
    "algorithm",
    "database",
    "network",
    "digital",
  ],
  animals: [
    "elephant",
    "butterfly",
    "dolphin",
    "penguin",
    "giraffe",
    "kangaroo",
    "octopus",
  ],
  food: [
    "chocolate",
    "sandwich",
    "banana",
    "strawberry",
    "spaghetti",
    "hamburger",
    "pizza",
  ],
  emotions: [
    "happiness",
    "excitement",
    "curiosity",
    "gratitude",
    "confidence",
    "enthusiasm",
  ],
  science: [
    "experiment",
    "hypothesis",
    "discovery",
    "research",
    "laboratory",
    "molecule",
  ],
};

// Difficulty-based word lists for better organization
const WORDS_BY_DIFFICULTY = {
  easy: SAFE_WORDS.filter((word) => word.length >= 4 && word.length <= 5),
  medium: SAFE_WORDS.filter((word) => word.length >= 6 && word.length <= 7),
  hard: SAFE_WORDS.filter((word) => word.length >= 8),
};

// Alternates: additional valid words not selected as puzzles but accepted as answers
// when they match the scrambled letters of the current puzzle word.
// Keep this list lowercase.
const ALTERNATE_WORDS = [
  // 4-letter alternates for existing easy words
  "sure",
  "user", // ruse
  "item",
  "lime", // time, mile
  "post",
  "pots",
  "spot",
  "tops", // stop
  "arts",
  "rats",
  "tars", // star
  "silo", // soil
  "from", // form
  "dear",
  "dare", // read
  "silt",
  "slit", // list
  "hare", // hear
  "evil",
  "veil",
  "vile", // live
  "nope",
  "peon", // open
  "palm", // lamp
  // 5-letter examples
  "pager", // grape
];

// Export for use in other modules (if using ES6 modules in future)
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    WORDS,
    SAFE_WORDS,
    ALTERNATE_WORDS,
    AMBIGUOUS_WORDS,
    WORD_CATEGORIES,
    WORDS_BY_DIFFICULTY,
  };
}
